development:
  app_name: Yottaa Link (test)
  app_url: https://api-dev.yottaa.com
  client_url: http://localhost/OAuth2PHPClient
  server_url: https://api-dev.yottaa.com
  client_id: 
  client_secret: 

staging:
  app_name: Yottaa Link (staging)
  app_url: https://api-dev.yottaa.com
  client_url: http://10.0.1.72/OAuth2PHPClient
  server_url: https://api-dev.yottaa.com
  client_id: 
  client_secret: 

production:
  app_name: Yottaa Link
  app_url: https://api-dev.yottaa.com
  client_url: https://api-dev.yottaa.com
  server_url: https://api-dev.yottaa.com
  client_id: 
  client_secret: 
